### PR TITLE
Add info and pwr entries.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
OK.

I have been working on the repeater WakeUp retry count system

Its working now. I'll push a PR soon so you can test it.

BTW. I'm using the same "Timeout" language string for this timeout, as I don't think its necessary to have a different string for this timeout

**Comment by f1rmb** [comment]
That's nice.
Yes, it's better to re-use existing strings, as also VP needs to be updated as well.

**Comment by rogerclarkmelbourne** [comment]
I think timeout just has a beep and no VP ;-)

**Comment by f1rmb** [comment]
Nope, now it has, but I enabled that when I added the error window timeout.

**Comment by rogerclarkmelbourne** [comment]
Ah,. LOL

I'll need to pull your changes then update my code.

**Comment by f1rmb** [comment]
Hi Roger,

  I just tried the timeout, and it works (with or without PTT Latch).

Cheers.
---
Daniel

**Comment by rogerclarkmelbourne** [comment]
Thanks. I forgot to test the latch

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
