### PR TITLE
Update user_power.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Umm

I replied to you email.

I found a local branch, which somehow was not merged

But I think there may be a typo 

is  this correct

info,,,Inforrmation


double r ??

**Comment by f1rmb** [comment]
Yeah, In this PR, I even added a comment about this (otherwise the r is silent).

**Comment by rogerclarkmelbourne** [comment]
Ah. OK. its for pronunciation

**Comment by f1rmb** [comment]
Yes.

**Comment by rogerclarkmelbourne** [comment]
Hopefully is OK now.

**Comment by f1rmb** [comment]
Thanks Roger 😉

**Pull request merged**
