### PR TITLE
Add overwrite_qm entry.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by OK2HAD** [comment]
Czech translate "overwrite_gm" = "Přepsat ?"

**Comment by rogerclarkmelbourne** [comment]
OK.

I've not had time to merge this yet, so I can manually update the Czech version after I merge it.

**Comment by OK2HAD** [comment]
Thanks Roger.

**Comment by f1rmb** [comment]
I've added the Czech translation to the PR. Thanks.

**Comment by rogerclarkmelbourne** [comment]
Thanks

**Pull request merged**
