### PR TITLE
Add bash builder script (supports language list from the command line).

### PR DESCRIPTION
**Pull request by f1rmb**
Make GD77VoicePromptsBuilder.py working under posix system too.

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Is this ready to merge ?

**Comment by f1rmb** [comment]
Yes it is ;-)

**Comment by rogerclarkmelbourne** [comment]
Thanks

Tested on Windows by deleting one mp3 file and it was download and converted and encoded etc OK

**Comment by f1rmb** [comment]
You mean the bash script ?

**Comment by rogerclarkmelbourne** [comment]
No.. Just the Python script

**Comment by f1rmb** [comment]
Oh, okay ;-)

**Comment by f1rmb** [comment]
And now, you can add comments in the CSV file.

**Pull request merged**
