### PR TITLE
Add battery_calibration VP.

### PR DESCRIPTION
**Pull request by f1rmb**

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
Thanks.

I used Google translate for the Japanese translation.  I have a contact in Japan who does the Japanese translations, so I will email him and ask him to check the recent changes to the firmware and VP texts

**Comment by f1rmb** [comment]
Hi Roger,

   Yeah, I didn't translate the Japanses as it's Katakana, and I'm not sure if Google do that.


Cheers.
...
Daniel

**Comment by f1rmb** [comment]
Just looked at the diff, it's not looking to be katakana ;-)

**Comment by f1rmb** [comment]
ROTFL. I think I'm missing some sleep, Katakana is irrelevant here :-D

**Comment by rogerclarkmelbourne** [comment]
I just used Google translate, I don't know if its correct .

I emailed the japanese translator to ask for him to check the recent changes

**Comment by f1rmb** [comment]
No no, forget about it, it was just a mistake from me. I had translation (text) in mind, not real spoken Japanese ;-)

**Pull request merged**
