### PR TITLE
Update wordlist_portugeuse_eurpoean.csv

### PR DESCRIPTION
**Pull request by ct1esj**
Some words did not have the real correspondence in our language. I took the liberty of correcting some, we'll see how they sound.
Thank you guys.
CT1ESJ - Henrique

### CODE REVIEW

**Comment by rogerclarkmelbourne** [comment]
You can test how they sound using  https://ttsmp3.com/

The audio will also be slightly degraded by the AMBE compression and also because of playback via the small speaker in the radio, but its still worth testing using TTSMP3

You can also build the voice pack yourself by installing Python, which is available for all major operating systems

**Comment by rogerclarkmelbourne** [comment]
I don't really want to merge this until you have confirmed that the text sounds OK in ttsmp3

**Comment by ct1esj** [comment]
Well, testing on TTSMP3 sounds great, then, as Roger commented, some quality loss will have to be dealt with, however, the corrections I made basically focus on items that were either not translated or the translation was not the correct one.

**Comment by f1rmb** [comment]
This PR now conflitcs.
Two entries has been modified in the repo (PROMPT_Minutes and PROMPT_Hours), which now are in upcase.

Cheers.
...
Daniel

**Comment by ct1esj** [comment]
> This PR now conflitcs.
> Two entries has been modified in the repo (PROMPT_Minutes and PROMPT_Hours), which now are in upcase.
> 
> Cheers.
> ...
> Daniel

I don't understand the conflict, everything seems to be in order

**Comment by f1rmb** [comment]
No, as Roger's repo has been updated, so your repository is now behind by two commits.

So you need to fetch and merge from upstream, first, check your modifications, then commit and push.

**Comment by f1rmb** [comment]
But if you have troubles doing this, I can raise a PR with your changes.

**Comment by ct1esj** [comment]
> But if you have troubles doing this, I can raise a PR with your changes.

I would appreciate it if you do it

**Comment by f1rmb** [comment]
Okay, it's done, PR #54

**Comment by ct1esj** [comment]
> Okay, it's done, PR #54

thanks for the kindness

**Comment by rogerclarkmelbourne** [comment]
OK.

I will merge the PR and build a new set of voice prompts later today.

**Pull request closed without merging**
